### ISSUE TITLE
LrcView Crash

### ISSUE THREAD

**Issue by cookiemouse** [wangchenyan/LrcView#4]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         java.util.ConcurrentModificationException
                                                                             at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:573)
                                                                             at me.wcy.lrcview.LrcView.initEntryList(LrcView.java:285)
                                                                             at me.wcy.lrcview.LrcView.onLrcLoaded(LrcView.java:206)
                                                                             at me.wcy.lrcview.LrcView.access$000(LrcView.java:27)
                                                                             at me.wcy.lrcview.LrcView$2.onPostExecute(LrcView.java:192)
                                                                             at me.wcy.lrcview.LrcView$2.onPostExecute(LrcView.java:183)
                                                                             at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                             at android.os.AsyncTask.access$500(AsyncTask.java:180)
                                                                             at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:148)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

情景：
多首歌曲，快迅切换（即快速加速不同歌词时）出现该bug。

**Comment by wangchenyan** [comment]
@cookiemouse 你好，我刚刚更新了代码(1.4.2)，做了线程安全处理，麻烦你再试下有没有问题。

**Comment by cookiemouse** [comment]
好的，可以请教一下你是怎么定位问题，以及怎么处理bug的吗？感觉你处理问题好快。

**Comment by wangchenyan** [comment]
@cookiemouse 过奖了，看log是ConcurrentModificationException异常，很容易就可以知道是线程安全问题，因此就做了线程安全处理。
