### ISSUE TITLE
越界异常

### ISSUE THREAD

**Issue by cookiemouse** [wangchenyan/LrcView#5]
FATAL EXCEPTION: main
                                                                           java.lang.IndexOutOfBoundsException: Invalid index 31, size is 0
                                                                               at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                               at java.util.ArrayList.get(ArrayList.java:308)
                                                                               at me.wcy.lrcview.LrcView.newlineAnimation(LrcView.java:314)
                                                                               at me.wcy.lrcview.LrcView.access$100(LrcView.java:27)
                                                                               at me.wcy.lrcview.LrcView$3.run(LrcView.java:302)
                                                                               at android.os.Handler.handleCallback(Handler.java:739)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5441)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

在变动播放进度时，出现越界异常，是否在使用的时候未进行边界判断？

**Comment by wangchenyan** [comment]
@cookiemouse 你好，请问你是否在使用1.4.1版本，如果是的话建议更新到1.4.2，该版本对线程安全做了处理。

**Comment by cookiemouse** [comment]
这个不是越界异常吗？

**Comment by wangchenyan** [comment]
就是因为线程安全问题导致数组越界。
